# Minimal pre-commit configuration for MVP development
# Only essential checks to prevent broken code

repos:
  # Basic file checks only
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: debug-statements  # Prevent accidentally committing print/breakpoint

  # Optional: Basic Python formatting (can be disabled)
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.11
        args: [--line-length=88]

# Configuration
default_language_version:
  python: python3.11
