name: Release

"on":
  push:
    tags:
      - 'v*'

# Рекомендуемые разрешения для безопасности
permissions:
  contents: write
  pull-requests: read

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
        prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
        make_latest: true
        discussion_category_name: "Releases"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
